"""
The free extraction path: read the PDF's own text layer.

WHY THIS EXISTS
    Most invoices a finance team receives are digital PDFs generated by a
    vendor's ERP, not photographs. Those files already contain the exact
    characters -- vendor name, every line item, every figure -- as text. Sending
    a *picture* of them to a vision model costs money, adds seconds of latency
    and introduces transcription risk, all to recover data that was never lost.

    So: try the text layer first. Fall back to vision only for documents that
    genuinely have no text -- scans and phone photos. On this project's own
    samples that is 2 of 3 files handled for nothing.

WHAT IT IS NOT
    This is not a universal invoice parser, and it does not pretend to be. It is
    a label-driven reader with a row heuristic and an honest `coverage` score.
    When coverage is low it says so and the pipeline escalates to vision. Every
    figure it produces goes through the same Pydantic schema and the same
    deterministic math audit as a vision extraction, so a bad parse is caught by
    arithmetic rather than shipped as fact.

THE ONE GENUINELY CLEVER BIT
    Swedish invoices use a space as the thousands separator, which makes a table
    row ambiguous as plain text:

        010 Frakt / Freight 1 450,00 450,00

    Is that qty 1 at 450,00 = 450,00? Or qty 1450,00 of something? Tokenising
    cannot tell. Arithmetic can: we generate the candidate readings and keep the
    one where quantity x unit_price actually equals the row total. The invoice's
    own maths disambiguates its own layout.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from decimal import Decimal
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from .schemas import to_decimal

# --------------------------------------------------------------------------
# Label vocabulary. Swedish + English first (the target market), then the
# neighbouring Nordic/German terms a Nordic freight or wholesale invoice
# actually arrives in. Deliberately no energy/utility vocabulary -- see the
# non-compete invariant in README.md.
# --------------------------------------------------------------------------
SUBTOTAL_LABELS = (
    "subtotal", "sub total", "sub-total", "net amount", "netto", "nettobelopp",
    "net total", "summa exkl", "exkl moms", "excl vat", "excluding vat",
    "delsumma", "varesum",
)
TAX_LABELS = (
    "vat", "moms", "mva", "alv", "mwst", "sales tax", "tax", "mervardesskatt",
    "mervärdesskatt", "moms 25", "vat 25",
)
TOTAL_LABELS = (
    "att betala", "total due", "total amount", "amount due", "grand total",
    "totalt att betala", "totalbelopp", "summa att betala", "to pay",
    "total", "totalt", "summa", "belopp att betala", "a betala",
)
INVOICE_NO_LABELS = (
    "invoice number", "invoice no", "invoice nr", "invoice #", "fakturanummer",
    "fakturanr", "faktura nr", "invoice", "faktura", "inv no", "no.", "nr.",
)
INVOICE_DATE_LABELS = (
    "invoice date", "fakturadatum", "date of invoice", "faktura datum",
    "issue date", "datum", "date",
)
DUE_DATE_LABELS = (
    "due date", "forfallodatum", "förfallodatum", "payment due", "due",
    "betalningsdag", "forfaller", "pay by",
)
CURRENCY_LABELS = ("currency", "valuta", "cur.", "ccy")
TAX_ID_LABELS = (
    "vat reg", "vat no", "vat number", "momsreg", "moms reg", "org.nr", "orgnr",
    "organisationsnummer", "vat id", "tax id", "momsregistreringsnummer", "vat",
)

# Company-form suffixes, used to spot the vendor name near the top of the page.
COMPANY_SUFFIXES = (
    "ab", "hb", "kb", "ekonomisk forening", "as", "asa", "aps", "a/s", "oy",
    "oyj", "ltd", "limited", "plc", "llp", "gmbh", "ag", "bv", "b.v.", "nv",
    "sarl", "sas", "sa", "srl", "spa", "inc", "inc.", "llc", "corp", "co.",
    "company", "holding", "group",
)

# A money-ish token: 1450 / 1450.00 / 1450,00 / 1,450.00 / (230.00) / -88.80
_MONEY_TOKEN = re.compile(r"^\(?-?\d{1,3}(?:[.,]\d{3})*(?:[.,]\d{1,2})?\)?$|^\(?-?\d+(?:[.,]\d{1,2})?\)?$")
# A bare thousands-group continuation: the "450,00" in "1 450,00"
_THOUSANDS_TAIL = re.compile(r"^\d{3}(?:[.,]\d{1,2})?$")
_DATE_TOKEN = re.compile(
    r"\b(\d{4}-\d{2}-\d{2}"
    r"|\d{1,2}[./-]\d{1,2}[./-]\d{2,4}"
    r"|\d{1,2}\s+[A-Za-z]{3,9}\s+\d{4}"
    r"|[A-Za-z]{3,9}\s+\d{1,2},?\s+\d{4})\b"
)
_ISO_CURRENCY = re.compile(r"\b(SEK|NOK|DKK|EUR|USD|GBP|CHF|PLN|CZK|JPY|ISK)\b")
_EU_VAT_ID = re.compile(r"\b([A-Z]{2}\s?[0-9][0-9\s]{6,14}[0-9A-Z]?)\b")
_PERCENT = re.compile(r"(\d{1,2}(?:[.,]\d{1,2})?)\s*%")
_LEADING_ROW_NO = re.compile(r"^(?:\d{1,4}[.)]?|[A-Z]{1,3}-?\d{1,5})\s+")
_ROW_TOLERANCE = Decimal("0.05")

# Column-header vocabulary, grouped by the column each word names. A line that
# names two or more different columns is the table header -- which is how we
# find where the line items start. Without this, an address block like
# "Box 1182" reads as a line item worth 1182.
_HEADER_COLUMNS = (
    ("description", "benamning", "benämning", "artikel", "vara", "item", "text"),
    ("qty", "quantity", "antal", "mangd", "mängd"),
    ("unit price", "a-pris", "a pris", "apris", "price", "pris", "rate", "unit"),
    ("amount", "belopp", "summa", "sum", "total", "netto"),
)

# Lines that are never line items, whatever else they look like.
_NOT_A_ROW = tuple(
    s.lower() for s in (
        "description", "benamning", "benämning", "artikel", "art ", "qty", "antal",
        "unit price", "a-pris", "belopp", "amount", "subtotal", "netto", "moms",
        "vat", "total", "totalt", "att betala", "summa", "page", "sida",
        "payment terms", "betalningsvillkor", "bankgiro", "iban", "bic", "swift",
        "fictional sample", "bill to", "faktureras", "leveransadress", "ship to",
        "invoice", "faktura", "org.nr", "momsreg", "vat reg", "currency", "valuta",
    )
)


@dataclass
class TextLayerExtraction:
    """A parse of the document's own text, plus an honest self-assessment."""

    data: Dict[str, Any]
    raw_text: str
    coverage: float
    found: List[str] = field(default_factory=list)
    missing: List[str] = field(default_factory=list)
    notes: List[str] = field(default_factory=list)

    # Fields that must be present for the result to be worth using instead of
    # paying a vision model. A total with no line items is not an extraction,
    # it is a guess.
    REQUIRED = ("total_amount", "line_items")

    @property
    def sufficient(self) -> bool:
        return all(f in self.found for f in self.REQUIRED)


# ---------------------------------------------------------------- text access
def page_texts(path: Path | str, max_pages: int = 3) -> List[str]:
    """Extract the embedded text of each page. Empty string where there is none."""
    path = Path(path)
    if path.suffix.lower() != ".pdf":
        return []

    import pypdfium2 as pdfium

    pdf = pdfium.PdfDocument(str(path))
    try:
        out: List[str] = []
        for index in range(min(len(pdf), max_pages)):
            textpage = pdf[index].get_textpage()
            try:
                out.append(textpage.get_text_range() or "")
            finally:
                # pypdfium2 objects are closed with the parent document, but
                # releasing the textpage early keeps memory flat on big files.
                del textpage
        return out
    finally:
        pdf.close()


def has_text_layer(path: Path | str, min_chars: int = 120) -> bool:
    """Is there enough real text here to be worth parsing instead of imaging?

    The threshold matters: a scanned invoice often carries a few stray
    characters (a digital stamp, a footer added by a mail gateway) without
    containing any of the actual invoice data.
    """
    try:
        return sum(len(t.strip()) for t in page_texts(path)) >= min_chars
    except Exception:
        return False


# ------------------------------------------------------------- number parsing
def _is_money(token: str) -> bool:
    return bool(_MONEY_TOKEN.match(token))


def _num(token: str) -> Optional[Decimal]:
    return to_decimal(token)


def _merge_candidates(tokens: List[str]) -> List[List[str]]:
    """Every plausible reading of trailing tokens where spaces may be separators.

    ["1", "450,00", "450,00"] can be read as three numbers, or as
    ["1 450,00", "450,00"] -- two. Both are returned; arithmetic picks.
    """
    results: List[List[str]] = [list(tokens)]
    for i in range(len(tokens) - 1):
        if re.fullmatch(r"-?\d{1,3}", tokens[i]) and _THOUSANDS_TAIL.match(tokens[i + 1]):
            merged = tokens[:i] + [f"{tokens[i]} {tokens[i + 1]}"] + tokens[i + 2:]
            if merged not in results:
                results.append(merged)
                # allow a second merge, e.g. "1 234 567,00"
                for deeper in _merge_candidates(merged):
                    if deeper not in results:
                        results.append(deeper)
    return results


def _parse_row(line: str) -> Optional[Dict[str, Any]]:
    """Read one table row. Returns None if the line is not a line item.

    Anchors from the RIGHT, because descriptions contain digits
    ("Kaffebonor Arabica 1kg", "Waiting time, 1.5 h") and the money columns do
    not move. Candidate readings are scored by whether qty x unit == total.
    """
    stripped = line.strip()
    if len(stripped) < 6:
        return None
    low = stripped.lower()
    if any(low.startswith(bad) or f" {bad}" == low[:len(bad) + 1] for bad in _NOT_A_ROW):
        return None

    tokens = stripped.split()
    # Longest run of money-ish tokens at the end of the line.
    tail_start = len(tokens)
    while tail_start > 0 and _is_money(tokens[tail_start - 1]):
        tail_start -= 1
    tail, head = tokens[tail_start:], tokens[:tail_start]
    if not tail or not head:
        return None

    best: Optional[Tuple[Decimal, Dict[str, Any]]] = None
    for candidate in _merge_candidates(tail):
        values = [_num(t) for t in candidate]
        if any(v is None for v in values):
            continue
        if len(values) >= 3:
            qty, unit, total = values[-3], values[-2], values[-1]
            if qty is None or unit is None or total is None:
                continue
            score = abs(qty * unit - total)
            row = {"quantity": str(qty), "unit_price": str(unit), "line_total": str(total)}
        elif len(values) == 2:
            # Two columns: assume unit price and amount, quantity implied 1.
            unit, total = values[-2], values[-1]
            score = abs(unit - total)
            row = {"quantity": None, "unit_price": str(unit), "line_total": str(total)}
        else:
            score = Decimal("9" * 12)
            row = {"quantity": None, "unit_price": None, "line_total": str(values[-1])}

        extra_head = candidate[:-3] if len(values) >= 3 else candidate[:-2]
        row["description"] = " ".join(head + extra_head).strip()
        if best is None or score < best[0]:
            best = (score, row)

    if best is None:
        return None

    score, row = best
    if score > _ROW_TOLERANCE:
        # No reading satisfies the row arithmetic. Keep the amount -- the audit's
        # sum(line items) vs subtotal check is still meaningful -- but do not
        # assert a quantity and unit price we could not confirm.
        last = _num(tail[-1])
        if last is None:
            return None
        row = {
            "description": " ".join(head + tail[:-1]).strip(),
            "quantity": None, "unit_price": None, "line_total": str(last),
        }

    row["description"] = _LEADING_ROW_NO.sub("", row["description"]).strip()
    if not row["description"]:
        return None
    return row


# -------------------------------------------------------------- field parsing
def _is_table_header(line: str) -> bool:
    """Does this line name two or more different table columns?"""
    low = f" {line.lower()} "
    hits = sum(
        any(re.search(rf"[\s|]{re.escape(word)}[\s|:]", low) for word in group)
        for group in _HEADER_COLUMNS
    )
    return hits >= 2


def _is_totals_line(line: str) -> bool:
    """Is this the start of the summary block that closes the table?"""
    low = line.lower()
    for labels in (SUBTOTAL_LABELS, TAX_LABELS, TOTAL_LABELS):
        if _label_hit(low, labels) is not None and any(
            _is_money(t) for t in line.split()
        ):
            return True
    return False


def _table_region(lines: List[str]) -> Tuple[int, int, bool]:
    """(start, end, found_header) for the slice of lines holding the line items.

    Anchoring on the header and the totals block is what keeps addresses,
    payment references and footers out of the line-item table.
    """
    start = None
    for index, line in enumerate(lines):
        if _is_table_header(line):
            start = index + 1
            break
    if start is None:
        return 0, len(lines), False
    end = len(lines)
    for index in range(start, len(lines)):
        if _is_totals_line(lines[index]):
            end = index
            break
    return start, end, True


def _label_hit(low_line: str, labels: Tuple[str, ...]) -> Optional[int]:
    """Index just past the longest matching label, or None."""
    best: Optional[int] = None
    for label in sorted(labels, key=len, reverse=True):
        pos = low_line.find(label)
        if pos != -1:
            end = pos + len(label)
            if best is None or end > best:
                best = end
    return best


def _amount_after(line: str, labels: Tuple[str, ...]) -> Optional[str]:
    """The last money value on a line carrying one of these labels."""
    end = _label_hit(line.lower(), labels)
    if end is None:
        return None
    tokens = line[end:].split()
    monies = [t for t in tokens if _is_money(t)]
    if not monies:
        return None
    # Re-merge space-separated thousands: "14 993,85" arrives as two tokens.
    for candidate in _merge_candidates(monies):
        if len(candidate) == 1:
            return candidate[0]
    return monies[-1]


def _date_after(line: str, labels: Tuple[str, ...]) -> Optional[str]:
    end = _label_hit(line.lower(), labels)
    if end is None:
        return None
    match = _DATE_TOKEN.search(line[end:])
    return match.group(1) if match else None


def _guess_vendor(lines: List[str]) -> Optional[str]:
    """The vendor's own name is almost always the first company-shaped line."""
    for line in lines[:12]:
        candidate = line.strip()
        if not (3 < len(candidate) < 80):
            continue
        low = candidate.lower().rstrip(".")
        if any(low.endswith(f" {suffix}") or low.endswith(suffix) for suffix in COMPANY_SUFFIXES):
            return candidate
    for line in lines[:6]:                       # fall back to the first real line
        candidate = line.strip()
        if 3 < len(candidate) < 80 and not _DATE_TOKEN.search(candidate):
            return candidate
    return None


def parse_text_layer(text: str) -> Dict[str, Any]:
    """Turn a page's text into a dict shaped like the extraction schema."""
    lines = [l for l in text.splitlines() if l.strip()]
    low_all = text.lower()

    data: Dict[str, Any] = {
        "vendor_name": _guess_vendor(lines),
        "vendor_tax_id": None, "invoice_no": None, "invoice_date": None,
        "due_date": None, "currency": None, "line_items": [],
        "subtotal": None, "tax_rate": None, "tax_amount": None, "total_amount": None,
    }

    # --- VAT / org number: prefer a properly formed EU VAT id
    for line in lines:
        if _label_hit(line.lower(), TAX_ID_LABELS) is not None:
            match = _EU_VAT_ID.search(line.upper())
            if match:
                data["vendor_tax_id"] = match.group(1).strip()
                break
    if data["vendor_tax_id"] is None:
        match = _EU_VAT_ID.search(text.upper())
        if match:
            data["vendor_tax_id"] = match.group(1).strip()

    # --- invoice number: the token after the label that is not a date
    for line in lines:
        end = _label_hit(line.lower(), INVOICE_NO_LABELS)
        if end is None:
            continue
        tail = line[end:].lstrip(" :.#-")
        if not tail or _DATE_TOKEN.match(tail):
            continue
        token = tail.split()[0].strip(":#.,")
        if token and any(ch.isdigit() for ch in token) and len(token) <= 32:
            data["invoice_no"] = token
            break

    # --- dates: due date first, so "due date" cannot be eaten by "date"
    for line in lines:
        if data["due_date"] is None:
            data["due_date"] = _date_after(line, DUE_DATE_LABELS)
    for line in lines:
        if data["invoice_date"] is None:
            found = _date_after(line, INVOICE_DATE_LABELS)
            if found and found != data["due_date"]:
                data["invoice_date"] = found
    if data["invoice_date"] is None:                  # any date at all, last resort
        match = _DATE_TOKEN.search(text)
        if match and match.group(1) != data["due_date"]:
            data["invoice_date"] = match.group(1)

    # --- currency
    for line in lines:
        end = _label_hit(line.lower(), CURRENCY_LABELS)
        if end is not None:
            match = _ISO_CURRENCY.search(line[end:].upper())
            if match:
                data["currency"] = match.group(1)
                break
    if data["currency"] is None:
        match = _ISO_CURRENCY.search(text.upper())
        if match:
            data["currency"] = match.group(1)
        elif "£" in text:
            data["currency"] = "GBP"
        elif "€" in text:
            data["currency"] = "EUR"
        elif "$" in text:
            data["currency"] = "USD"

    # --- totals block. Order matters: "Subtotal" contains "total", so the
    #     subtotal labels must be consumed before the total labels are tried.
    for line in lines:
        low = line.lower()
        if data["subtotal"] is None and _label_hit(low, SUBTOTAL_LABELS) is not None:
            data["subtotal"] = _amount_after(line, SUBTOTAL_LABELS)
            continue
        if data["tax_amount"] is None and _label_hit(low, TAX_LABELS) is not None:
            amount = _amount_after(line, TAX_LABELS)
            if amount is not None:
                data["tax_amount"] = amount
                rate = _PERCENT.search(line)
                if rate and data["tax_rate"] is None:
                    data["tax_rate"] = rate.group(1).replace(",", ".")
            continue
        if data["total_amount"] is None and _label_hit(low, TOTAL_LABELS) is not None:
            data["total_amount"] = _amount_after(line, TOTAL_LABELS)

    if data["tax_rate"] is None:
        rate = _PERCENT.search(low_all)
        if rate:
            data["tax_rate"] = rate.group(1).replace(",", ".")

    # --- line items, taken only from between the column header and the totals
    start, end, found_header = _table_region(lines)
    rows: List[Dict[str, Any]] = []
    for line in lines[start:end]:
        row = _parse_row(line)
        if row is None:
            continue
        if not found_header and row["quantity"] is None and row["unit_price"] is None:
            # No header to anchor on, and only one money column on the line --
            # too weak to call a line item. This is what an address ("Box 1182")
            # or a payment reference looks like.
            continue
        rows.append(row)
    data["line_items"] = rows
    return data


def extract_from_text_layer(
    path: Path | str, max_pages: int = 3
) -> Optional[TextLayerExtraction]:
    """Parse a document from its own text. None when there is no text to parse."""
    texts = page_texts(path, max_pages=max_pages)
    combined = "\n".join(t for t in texts if t.strip())
    if len(combined.strip()) < 120:
        return None

    data = parse_text_layer(combined)

    key_fields = ("vendor_name", "invoice_no", "invoice_date", "currency",
                  "subtotal", "tax_amount", "total_amount", "line_items")
    found = [f for f in key_fields if data.get(f)]
    missing = [f for f in key_fields if not data.get(f)]

    notes = [
        f"read from the PDF's own text layer across {len(texts)} page(s) - "
        f"no vision model, no API call, no cost"
    ]
    if missing:
        notes.append("text layer did not yield: " + ", ".join(missing))

    return TextLayerExtraction(
        data=data,
        raw_text=combined,
        coverage=len(found) / len(key_fields),
        found=found,
        missing=missing,
        notes=notes,
    )
